/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'Custom';

  static const IconData github_circled =
      const IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData trello = const IconData(0xf181, fontFamily: _kFontFam);
}
