/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();


  static const _kFontFam = 'Custom';

  static const IconData restaurant_menu = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData food = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chart_line = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData feedback = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData format_list_bulleted = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData basket = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData roast_turkey = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData harvest = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData meat = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData carrot = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData fish = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData baguette = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData cereals = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData cheese = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData a004_pot = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData a005_stew = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData a006_pot = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData a007_pan = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData a008_stew = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData a009_teapot = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData a010_teapot = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData a011_tea = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData a012_lemon = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData a013_mixer = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData a014_cupcake = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData a015_cupcake = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData a016_doughnut = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData a017_doughnut = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData a018_doughnut = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData a019_pancakes = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData a020_cake = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData a021_pancakes = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData a022_pie = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData a023_peach = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData a024_pie = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData a025_ice_cream = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData a026_ice_cream = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData a027_ice_cream = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData a028_ice_cream = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData a029_ice_cream = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData a030_ice_cream = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData a031_ice_cream = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData a032_ice_cream = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData a033_ice_cream = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData a034_apple = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData a035_ice_cream = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData a036_cupcake = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData a037_sorbet = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData a038_ice_cream = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData a039_ice_cream = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData a040_ice_cream = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData a041_ice_cream = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData a042_ice_cream = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData a043_chips = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData a044_biscuit = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData a045_pear = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData a046_coffee = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData a047_fries = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData a048_taco = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData a049_sandwich = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData a050_hamburguer = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData a051_hamburguer = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData a052_sandwich = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData a053_hot_dog = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData a054_baguette = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData a055_bread = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData a056_blueberries = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData a057_corndog = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData a058_honey = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData a059_honey = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData a060_jam = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData a061_jam = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData a062_jelly = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData a063_butter = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData a064_mustard = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData a065_potatoes = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData a066_pickles = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData a067_pineapple = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData a068_potatoes = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData a069_chocolate = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData a070_croissant = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData a071_candy = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData a072_toffee = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData a073_cookies = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData a074_gingerbread = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData a075_popsicle = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData a076_jawbreaker = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData a077_pasta = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData a078_avocado = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData a079_grinder = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData a080_dish = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData a081_food = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData a082_turkey = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData a083_hot_dog = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData a084_milk = const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData a085_pudding = const IconData(0xe861, fontFamily: _kFontFam);
  static const IconData a086_steak = const IconData(0xe862, fontFamily: _kFontFam);
  static const IconData a087_egg = const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData a088_meat = const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData a089_orange = const IconData(0xe865, fontFamily: _kFontFam);
  static const IconData a090_toaster = const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData a091_toast = const IconData(0xe867, fontFamily: _kFontFam);
  static const IconData a092_bread = const IconData(0xe868, fontFamily: _kFontFam);
  static const IconData a093_milk = const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData a094_pretzel = const IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData a095_salad = const IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData a096_eggs = const IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData a097_frappe = const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData a098_risotto = const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData a099_bacon = const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData a100_banana = const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData a101_kebab = const IconData(0xe871, fontFamily: _kFontFam);
  static const IconData a102_pizza = const IconData(0xe872, fontFamily: _kFontFam);
  static const IconData a103_pizza = const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData a104_pizza = const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData a105_pizza = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData a106_pizza = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData a107_ham = const IconData(0xe877, fontFamily: _kFontFam);
  static const IconData a108_sausage = const IconData(0xe878, fontFamily: _kFontFam);
  static const IconData a109_cheese = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData a110_cheese = const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData a111_pomegranate = const IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData a112_grapes = const IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData a113_salami = const IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData a114_wrap = const IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData a115_sushi = const IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData a116_noodles = const IconData(0xe880, fontFamily: _kFontFam);
  static const IconData a117_sushi = const IconData(0xe881, fontFamily: _kFontFam);
  static const IconData a118_sushi = const IconData(0xe882, fontFamily: _kFontFam);
  static const IconData a119_kebab = const IconData(0xe883, fontFamily: _kFontFam);
  static const IconData a120_water = const IconData(0xe884, fontFamily: _kFontFam);
  static const IconData a121_flour = const IconData(0xe885, fontFamily: _kFontFam);
  static const IconData a122_can = const IconData(0xe886, fontFamily: _kFontFam);
  static const IconData a123_coconut = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData a124_can = const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData a125_chef = const IconData(0xe889, fontFamily: _kFontFam);
  static const IconData a126_dishes = const IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData a127_rice = const IconData(0xe88b, fontFamily: _kFontFam);
  static const IconData a128_cereals = const IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData a129_flour = const IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData a130_kitchen = const IconData(0xe88e, fontFamily: _kFontFam);
  static const IconData a131_octopus = const IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData a132_salmon = const IconData(0xe890, fontFamily: _kFontFam);
  static const IconData a133_shrimp = const IconData(0xe891, fontFamily: _kFontFam);
  static const IconData a134_garlic = const IconData(0xe892, fontFamily: _kFontFam);
  static const IconData a135_fish = const IconData(0xe893, fontFamily: _kFontFam);
  static const IconData a136_bowl = const IconData(0xe894, fontFamily: _kFontFam);
  static const IconData a137_pie = const IconData(0xe895, fontFamily: _kFontFam);
  static const IconData a138_meat = const IconData(0xe896, fontFamily: _kFontFam);
  static const IconData a139_kebab = const IconData(0xe897, fontFamily: _kFontFam);
  static const IconData a140_coffee = const IconData(0xe898, fontFamily: _kFontFam);
  static const IconData a141_mustard = const IconData(0xe899, fontFamily: _kFontFam);
  static const IconData a142_mustard = const IconData(0xe89a, fontFamily: _kFontFam);
  static const IconData a143_oil = const IconData(0xe89b, fontFamily: _kFontFam);
  static const IconData a144_knives = const IconData(0xe89c, fontFamily: _kFontFam);
  static const IconData a145_potatoes = const IconData(0xe89d, fontFamily: _kFontFam);
  static const IconData a146_meat = const IconData(0xe89e, fontFamily: _kFontFam);
  static const IconData a147_carrot = const IconData(0xe89f, fontFamily: _kFontFam);
  static const IconData a148_pepper = const IconData(0xe8a0, fontFamily: _kFontFam);
  static const IconData a149_onion = const IconData(0xe8a1, fontFamily: _kFontFam);
  static const IconData a150_chives = const IconData(0xe8a2, fontFamily: _kFontFam);
  static const IconData a151_olives = const IconData(0xe8a3, fontFamily: _kFontFam);
  static const IconData a152_cauliflower = const IconData(0xe8a4, fontFamily: _kFontFam);
  static const IconData a153_broccoli = const IconData(0xe8a5, fontFamily: _kFontFam);
  static const IconData a154_radish = const IconData(0xe8a6, fontFamily: _kFontFam);
  static const IconData a155_onion = const IconData(0xe8a7, fontFamily: _kFontFam);
  static const IconData a156_corn = const IconData(0xe8a8, fontFamily: _kFontFam);
  static const IconData a157_cucumber = const IconData(0xe8a9, fontFamily: _kFontFam);
  static const IconData a158_cabbage = const IconData(0xe8aa, fontFamily: _kFontFam);
  static const IconData a159_aubergine = const IconData(0xe8ab, fontFamily: _kFontFam);
  static const IconData a160_chili = const IconData(0xe8ac, fontFamily: _kFontFam);
  static const IconData a161_tomato = const IconData(0xe8ad, fontFamily: _kFontFam);
  static const IconData a162_mushroom = const IconData(0xe8ae, fontFamily: _kFontFam);
  static const IconData a163_mushrooms = const IconData(0xe8af, fontFamily: _kFontFam);
  static const IconData a164_pumpkin = const IconData(0xe8b0, fontFamily: _kFontFam);
  static const IconData a165_cherries = const IconData(0xe8b1, fontFamily: _kFontFam);
  static const IconData a166_peas = const IconData(0xe8b2, fontFamily: _kFontFam);
  static const IconData a167_beans = const IconData(0xe8b3, fontFamily: _kFontFam);
  static const IconData a168_pistachio = const IconData(0xe8b4, fontFamily: _kFontFam);
  static const IconData a169_seeds = const IconData(0xe8b5, fontFamily: _kFontFam);
  static const IconData a170_fig = const IconData(0xe8b6, fontFamily: _kFontFam);
  static const IconData a171_grain = const IconData(0xe8b7, fontFamily: _kFontFam);
  static const IconData a172_oat = const IconData(0xe8b8, fontFamily: _kFontFam);
  static const IconData a173_asparagus = const IconData(0xe8b9, fontFamily: _kFontFam);
  static const IconData a174_salad = const IconData(0xe8ba, fontFamily: _kFontFam);
  static const IconData a175_coffee = const IconData(0xe8bb, fontFamily: _kFontFam);
  static const IconData a176_raspberry = const IconData(0xe8bc, fontFamily: _kFontFam);
  static const IconData a177_hazelnut = const IconData(0xe8bd, fontFamily: _kFontFam);
  static const IconData a178_spoon = const IconData(0xe8be, fontFamily: _kFontFam);
  static const IconData a179_fork = const IconData(0xe8bf, fontFamily: _kFontFam);
  static const IconData a180_knife = const IconData(0xe8c0, fontFamily: _kFontFam);
  static const IconData a181_teaspoon = const IconData(0xe8c1, fontFamily: _kFontFam);
  static const IconData a182_knife = const IconData(0xe8c2, fontFamily: _kFontFam);
  static const IconData a183_spatula = const IconData(0xe8c3, fontFamily: _kFontFam);
  static const IconData a184_knife = const IconData(0xe8c4, fontFamily: _kFontFam);
  static const IconData a185_butcher = const IconData(0xe8c5, fontFamily: _kFontFam);
  static const IconData a186_cutlery = const IconData(0xe8c6, fontFamily: _kFontFam);
  static const IconData a187_strawberry = const IconData(0xe8c7, fontFamily: _kFontFam);
  static const IconData a188_whisk = const IconData(0xe8c8, fontFamily: _kFontFam);
  static const IconData a189_ladle = const IconData(0xe8c9, fontFamily: _kFontFam);
  static const IconData a190_slotted_spoon = const IconData(0xe8ca, fontFamily: _kFontFam);
  static const IconData a191_spatula = const IconData(0xe8cb, fontFamily: _kFontFam);
  static const IconData a192_knife = const IconData(0xe8cc, fontFamily: _kFontFam);
  static const IconData a193_pizza = const IconData(0xe8cd, fontFamily: _kFontFam);
  static const IconData a194_rolling_pin = const IconData(0xe8ce, fontFamily: _kFontFam);
  static const IconData a195_ornating = const IconData(0xe8cf, fontFamily: _kFontFam);
  static const IconData a196_tenderizer = const IconData(0xe8d0, fontFamily: _kFontFam);
  static const IconData a197_corckscrew = const IconData(0xe8d1, fontFamily: _kFontFam);
  static const IconData a198_apple = const IconData(0xe8d2, fontFamily: _kFontFam);
  static const IconData a199_bread = const IconData(0xe8d3, fontFamily: _kFontFam);
  static const IconData a200_glass = const IconData(0xe8d4, fontFamily: _kFontFam);
  static const IconData a201_mug = const IconData(0xe8d5, fontFamily: _kFontFam);
  static const IconData a202_cup = const IconData(0xe8d6, fontFamily: _kFontFam);
  static const IconData a203_spaguetti = const IconData(0xe8d7, fontFamily: _kFontFam);
  static const IconData a204_grater = const IconData(0xe8d8, fontFamily: _kFontFam);
  static const IconData a205_water = const IconData(0xe8d9, fontFamily: _kFontFam);
  static const IconData a206_bowl = const IconData(0xe8da, fontFamily: _kFontFam);
  static const IconData a207_strainer = const IconData(0xe8db, fontFamily: _kFontFam);
  static const IconData a208_watermelon = const IconData(0xe8dc, fontFamily: _kFontFam);
  static const IconData a209_spices = const IconData(0xe8dd, fontFamily: _kFontFam);
  static const IconData a210_glass = const IconData(0xe8de, fontFamily: _kFontFam);
  static const IconData a211_glass = const IconData(0xe8df, fontFamily: _kFontFam);
  static const IconData a212_glass = const IconData(0xe8e0, fontFamily: _kFontFam);
  static const IconData a213_glass = const IconData(0xe8e1, fontFamily: _kFontFam);
  static const IconData a214_glass = const IconData(0xe8e2, fontFamily: _kFontFam);
  static const IconData a215_glass = const IconData(0xe8e3, fontFamily: _kFontFam);
  static const IconData a216_thermos = const IconData(0xe8e4, fontFamily: _kFontFam);
  static const IconData a217_pint = const IconData(0xe8e5, fontFamily: _kFontFam);
  static const IconData a218_scale = const IconData(0xe8e6, fontFamily: _kFontFam);
  static const IconData a219_lemon = const IconData(0xe8e7, fontFamily: _kFontFam);
  static const IconData a220_coffee_maker = const IconData(0xe8e8, fontFamily: _kFontFam);
  static const IconData a221_groceries = const IconData(0xe8e9, fontFamily: _kFontFam);
  static const IconData a222_coffee = const IconData(0xe8ea, fontFamily: _kFontFam);
  static const IconData a223_coffee = const IconData(0xe8eb, fontFamily: _kFontFam);
  static const IconData a224_tea = const IconData(0xe8ec, fontFamily: _kFontFam);
  static const IconData a225_salt = const IconData(0xe8ed, fontFamily: _kFontFam);
  static const IconData a226_pepper = const IconData(0xe8ee, fontFamily: _kFontFam);
  static const IconData a227_pasta = const IconData(0xe8ef, fontFamily: _kFontFam);
  static const IconData a228_candy = const IconData(0xe8f0, fontFamily: _kFontFam);
  static const IconData a229_can = const IconData(0xe8f1, fontFamily: _kFontFam);
  static const IconData a230_lime = const IconData(0xe8f2, fontFamily: _kFontFam);
  static const IconData a001_bottles = const IconData(0xe8f3, fontFamily: _kFontFam);
  static const IconData a002_boiled = const IconData(0xe8f4, fontFamily: _kFontFam);
  static const IconData a003_pot = const IconData(0xe8f5, fontFamily: _kFontFam);
  static const IconData github_circled = const IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData trello = const IconData(0xf181, fontFamily: _kFontFam);


}
